# Generated by Django 6.0 on 2026-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_band', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Upcoming', 'Upcoming'), ('Closed', 'Closed')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='category',
            field=models.CharField(choices=[('Large Cap', 'Large Cap'), ('Small Cap', 'Small Cap'), ('Hybrid', 'Hybrid'), ('Sectoral', 'Sectoral')], default='Large Cap', max_length=20),
        ),
        migrations.AddField(
            model_name='mutualfund',
            name='one_year_return',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='mutualfund',
            name='nav',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
