# Generated by Django 6.0 on 2026-01-05 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_portfolio_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='market',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AlterField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core.portfolio'),
        ),
    ]
