# Generated by Django 4.0 on 2026-01-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_demataccount_portfolio_created_at_portfolio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='My Portfolio', max_length=100),
        ),
    ]
