# Generated by Django 6.0 on 2026-02-10 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_stock_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IPO_APPLY', 'IPO Apply'), ('IPO_REFUND', 'IPO Refund'), ('IPO_ALLOT', 'IPO Allotment'), ('STOCK_BUY', 'Stock Buy'), ('STOCK_SELL', 'Stock Sell'), ('WALLET_ADD', 'Wallet Add')], max_length=20),
        ),
    ]
